import fs from "node:fs";
import { catalog } from "../src/data/catalog.ts";

/** Haus, Familie, Wer — aus der Namensbereinigung. Kollisionen = Verwandtschaft. */
const HOUSES = {
  "1": ["Haus Wendisch", "Wendisch", "Gerlach Wendisch (30), Straßenname Laus, Bettler, allein."],
  "70": ["Haus Habicht", "Habicht", "Grete Habicht, Witwe, zwei Kinder. Nachbar Anton Reske borgt."],
  "2": ["Haus Brack", "Brack", "Jaan (34), Sanna (31), Birk (8) Brack."],
  "3": ["Haus Rehbach", "Rehbach", "Wagen und Ochsen der Familie Rehbach. Hannes wohnt Torstraße 5."],
  "71": ["Haus Lenz", "Lenz", "Familie Lenz, Zuzügler. Hebamme Runa Lenz."],
  "72": ["Reisighütte", "", "Colm, Hirte ohne Herde. Nicht registriert."],
  "4": ["Haus Winter", "Winter", "Hilde (36), Anni (12) Winter."],
  "5": ["Haus —", "", "niemand. Dach eingefallen."],
  Shallya: ["Shallya-Nische", "", "Kranke, Mütter. Bruder Otmar kommt sonntags."],
  Wegschrein: ["Wegschrein", "", "Reisende, Kinder."],
  "6": ["Haus —", "", "niemand. Informeller Ranald-Schrein."],
  Nordtor: ["Nordtor", "", "Wächter Bram Holt, Zöllner, Boten. Arne Falk dient im Zollhaus."],
  "7": ["Zollhaus Falk", "Falk", "Arne Falk, Zoll. Wohnt Torstraße 8."],
  "8": ["Haus Wendlandt", "Wendlandt", "Detlef (43), Mara (39), Ben (13) Wendlandt."],
  "9": ["Haus Ahlgrimm", "Ahlgrimm", "Gerd (41), Hanne (38), Lina (10) Ahlgrimm."],
  "10": ["Haus Brandner", "Brandner", "Konrad (45), Rita (42), Jan (17) Brandner."],
  "11": ["Haus Rehbach", "Rehbach", "Hannes (40), Berta (37), Ulf (14), Mina (8) Rehbach."],
  "12": ["Haus Krell", "Krell", "Rudi (35), Nadja (32), Kilian (9), Fine (5) Krell."],
  "13": ["Haus Sorge", "Sorge", "Ewald (37), Sigrid (34) Sorge."],
  "14": ["Haus Falk", "Falk", "Arne (38), Dora (35), Finn (7) Falk."],
  "15": ["Brunnenhaus", "", "niemand wohnt. Mägde, Wache, Kinder."],
  "73": ["Haus Rombach", "Rombach", "Familie Rombach, Geselle Anno, Gläubiger Fenn."],
  "74": ["Haus Odenthal", "Odenthal", "Balder Odenthal, Pächter."],
  "75": ["Haus Dorn", "Dorn", "Kaufmann Albrecht Dorn, Schreiber Cyprian. Bruder des Notars Leopold Dorn."],
  "76": ["Haus Reichenbach", "Reichenbach", "Familie Reichenbach mit Gesinde."],
  "77": ["Haus Krautwig / Senft", "Krautwig; Senft", "Unten Krautwig, oben Senft. Sie grüßen sich nicht."],
  "78": ["Haus Hoge", "Hoge", "Anselm Hoge, Herberge für Verspätete."],
  "79": ["Mietkaserne", "", "Aufseher Rutger Bock. Mietvolk wechselt."],
  "80": ["Haus Reske", "Reske", "Holzknecht Anton Reske, Familie. Borgt bei Habicht."],
  "81": ["Haus Ohlendorf", "Ohlendorf", "Nebenlinie des Stadtrats Ohlendorf. Wollen den Zaun höher."],
  "82": ["Haus Ahrens", "Ahrens", "Witwe Trudel Ahrens, Enkel Peter."],
  "NW-Turm": ["Nordwestturm", "", "Wächter Jörg Mehl, oft allein."],
  "16": ["Kaufmannsgilde", "Reichart", "Wilhelm Reichart, Gildemeister. Sitz, nicht Wohnung."],
  "17": ["Haus Ohlendorf", "Ohlendorf", "Reiner (48), Klara (43), Anike (16) Ohlendorf. Stadtrat."],
  "18": ["Sigmarstempel", "Amsberg", "Vater Brant Amsberg (53), Novize Jost (19)."],
  Marktbrunnen: ["Marktbrunnen", "", "Krämer, Kinder, Wache."],
  Pranger: ["Pranger", "", "Öffentliche Strafe. Scherge."],
  "21": ["Ratshaus", "Kirchweger", "Helmuth (46), Mathilde (42), Johann (18) Kirchweger."],
  "19": ["Waage", "", "Wäger Emil Kant, streitende Krämer."],
  "20": ["Schreiberstube", "Dorn", "Notar Leopold (39), Agnes (34) Dorn. Bruder von Albrecht Dorn am Tor."],
  "22": ["Haus Reichart", "Reichart", "Berthold (30), Saskia (27), Emmerich (6), Liese (3). Sohn des Gildemeisters."],
  "23": ["Haus Marsold", "Marsold", "Magnus (44), Ute (40) Marsold, Geldwechsel."],
  "25": ["Handwerkerzunft", "", "Sammelzunft. Keine Wohnfamilie."],
  "24": ["Zunftherberge", "", "Durchreisende Gesellen, Lehrling unten."],
  "26": ["Zunftlager", "", "Nachtwächter Eckhard Stumm. Niemand wohnt."],
  "27": ["Haus Rautenberg", "Rautenberg", "Franz (36), Nela (33), Timo (9) Rautenberg."],
  "28": ["Haus Vetterlein", "Vetterlein", "Wirt, Spieler, Leute vom Schatten."],
  "29": ["Haus Reichart", "Reichart", "Wilhelm (54), Elsa (50) Reichart."],
  "30": ["Leeres Kontor", "", "niemand. Auswärtige Kompanie, seit einem Jahr weg."],
  "83": ["Zunftarchiv", "", "niemand wohnt. Steuerlisten, Meisterbriefe."],
  "84": ["Haus Halbritter", "Halbritter", "Kaspar (41), Hilda (38); Pieter (15) auf der Reik."],
  "87": ["Haus Kellinghaus", "Kellinghaus", "Witwe, Schreiber."],
  "88": ["Haus Pergel", "Pergel", "Kleinhändler."],
  "31": ["Hufschmiede Vollrath", "Vollrath", "Bodo Vollrath schmiedet hier, wohnt Schmiedezeile 3. Lehrling am Blasebalg."],
  "32": ["Haus Grenzow", "Grenzow", "Ulrich (49), Kathe (46) Grenzow. Beliefert die Wache."],
  "33": ["Haus Vollrath", "Vollrath", "Bodo (47), Gerda (44). Tochter Ilse (18) in Bögenhafen."],
  "34": ["Stall der Schmiede", "", "Knecht, Pferde."],
  "35": ["Kohlenlager", "", "niemand wohnt. Kohle der Meister."],
  "36": ["Haus Osterhagen", "Osterhagen", "Timo (18), Neffe der Vollraths."],
  "89": ["Haus Bregenz", "Bregenz", "Zweitfamilie der Schmiede, Gläubiger, Magd."],
  "90": ["Haus Wolfram", "Wolfram", "Wulf (32), Mark (29) Wolfram, Gesellen. Ulric privat."],
  "105": ["Haus Wolfram", "Wolfram", "Gesellenfrau und Kind. Nebenhaus zu den Wolfram-Gesellen."],
  "37": ["Weberei Hessler", "Hessler", "Webstuhl. Familie Hessler wohnt Weberweg 3."],
  "38": ["Schneiderei Dietwald", "Dietwald", "Laden. Familie wohnt Weberweg 4."],
  "39": ["Haus Dietwald", "Dietwald", "Else (36) Meisterin, Pieter (38), Lena (14), Karl (11)."],
  "40": ["Haus Hessler", "Hessler", "Eberhard (48), Lotte (45), Rike (20) Hessler."],
  "41": ["Haus Aldenrath", "Aldenrath", "Niko (35), Wera (32) Aldenrath."],
  Holzlager: ["Holzlager", "", "Holzknecht, Weber."],
  "85": ["Haus Ilgen", "Ilgen", "Weberin allein."],
  "86": ["Haus Berken", "Berken", "Jäger der webt, Frau die flickt."],
  "91": ["Haus Krosigk", "Krosigk", "Randweber."],
  "92": ["Langhaus der Spinner", "", "Spinnerinnen, Kollektiv."],
  "42": ["Krämerladen Grasegger", "Grasegger", "Gemischtwaren. Familie wohnt Krämerstraße 3."],
  "43": ["Kräuterhandlung Ahlborn", "Ahlborn", "Maren hinter der Theke. Wohnt Krämerstraße 4."],
  "44": ["Haus Grasegger", "Grasegger", "Hartmut (42), Ida (39), Paul (12) Grasegger."],
  "45": ["Haus Ahlborn", "Ahlborn", "Maren (40), Jette (16) Ahlborn."],
  "46": ["Haus Steigerwald", "Steigerwald", "Simon (38), Eva (34) Steigerwald."],
  "47": ["Leerer Laden", "", "niemand. Ehemals Hutmacher."],
  "93": ["Haus Pentling", "Pentling", "Händler, Magd auf der Treppe."],
  "94": ["Haus Werle", "Werle", "Krämer, der den Markt meidet."],
  "48": ["Gerberei Duerrwang", "Duerrwang", "Gruben, Häute. Familie wohnt Gerbergasse 2."],
  "49": ["Haus Duerrwang", "Duerrwang", "Dietrich (50), Hedwig (47) Duerrwang."],
  "50": ["Haus Kaltenbrunn", "Kaltenbrunn", "Lutz (31), Enno (28) Kaltenbrunn."],
  "51": ["Häutelager", "", "Lehrling, Ratte. Niemand wohnt."],
  "52": ["Töpferei Moosbrugger", "Moosbrugger", "Ofen. Familie wohnt Töpfergasse 2."],
  "53": ["Haus Moosbrugger", "Moosbrugger", "Meinhard (44), Birgit (41), Ada (13) Moosbrugger."],
  "54": ["Haus Falkenrath", "Falkenrath", "Jori (17). Nicht der Sohn des Meisters."],
  "95": ["Haus Grothe", "Grothe", "Familie Grothe, hohe Holzschuhe."],
  "96": ["Haus Winkelmann", "Winkelmann", "Witwe Winkelmann."],
  Waschsteg: ["Waschsteg", "", "Wäscherinnen, Gerberknecht."],
  Osttor: ["Osttor", "", "Totengräber, Trauerzug. Wächter Heinz Laub steht ungern hier."],
  "55": ["Haus Wehming", "Wehming", "Silas (46), Odila (42) Wehming. Dienst Morr."],
  "56": ["Morr-Kapelle", "Amsel", "Schwester Miren Amsel (52), Ordensname Ewig."],
  Garten: ["Morrs Garten", "", "Trauernde, Raben, Gärtner."],
  "104": ["Haus Amsel", "Amsel", "Nebenhaus. Leichenwäscherin, Verwandte der Priesterin."],
  "SW-Turm": ["Südwestturm", "", "Wächterin Lena Kranz, oft allein, sieht zum Garten."],
  "57": ["Taverne Dunkelgrund", "Dunkelgrund", "Rolf zapft. Ranald im Hinterzimmer. Wohnen Schlemmergasse 3."],
  "58": ["Haus Sonnleitner", "Sonnleitner", "Thea (39), Kira (18) Sonnleitner."],
  "59": ["Haus Brandholz", "Brandholz", "Magda (64). Mann Ewald †2501."],
  "97": ["Haus Dunkelgrund", "Dunkelgrund", "Rolf (42), Janna (38), Nils (12)."],
  "100": ["Rot-Stein-Haus", "", "Alte, Kind, Brennholz."],
  "60": ["Leere Hütte", "", "niemand dauerhaft."],
  "61": ["Haus Lettner", "Lettner", "Kranke, Pflegerin ohne Orden."],
  "62": ["Hütte der Ordnung", "", "Krumm (42), Fips (24), Auge (47). Geburtsnamen unbekannt."],
  "63": ["Leere Hütte", "", "niemand. Dach ein, Brandnarbe."],
  "64": ["Nagelhaus", "", "Durchzügler, ein Zimmermann."],
  "65": ["Leere Hütte", "", "niemand. Tür vernagelt."],
  "66": ["Hütte Dünn", "", "Ivo (32), Straßenname Dünn, allein. Geburtsname offen."],
  "67": ["Gemeinschaftsbrunnen", "", "Kinder, Alte."],
  Mistplatz: ["Mistplatz", "", "Raben, Knecht, Sucher."],
  "98": ["Haus Reifenberg", "Reifenberg", "Wenzel (37), Ulla (34), Pia (10) Reifenberg."],
  "99": ["Schiefer Schuppen", "", "Niemand dauerhaft."],
  "101": ["Reisigschuppen", "", "Holzsammler, Schläfer an der Mauer."],
  "102": ["Schiefer Anbau", "", "Familie auf Abruf."],
  "68": ["Haus Stolzenau", "Stolzenau", "Abel und Mira Stolzenau, verschwunden 2506."],
  "69": ["Letztes leerstehendes Gebäude", "", "niemand. Nachbarn meiden es."],
  "103": ["Bretterverschlag", "", "Niemand, Ratte."],
  "SO-Turm": ["Südostturm", "", "Wächter Otto Ried. Fürchtet den Wald mehr als die Stadt."],
};

for (const p of catalog.places) {
  const row = HOUSES[p.id];
  if (!row) continue;
  p.haus = row[0];
  p.familie = row[1];
  p.wer = row[2];
  if (row[0] && p.kanon) {
    p.kanon = p.kanon.replace(/· Haus [^·]+$/i, `· ${row[0]}`);
  }
}

const out = `import type { Catalog } from "@/lib/types";\n\nexport const catalog: Catalog = ${JSON.stringify(catalog, null, 2)};\n`;
fs.writeFileSync(new URL("../src/data/catalog.ts", import.meta.url), out);
const missing = catalog.places.filter((p) => !HOUSES[p.id]).map((p) => p.id);
console.log("patched", Object.keys(HOUSES).length, "missing", missing);
