/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbgleichRouteImport } from './routes/abgleich'
import { Route as EingangRouteImport } from './routes/eingang'
import { Route as StilRouteImport } from './routes/stil'
import { Route as BezirkKeyRouteImport } from './routes/bezirk.$key'
import { Route as OrtIdRouteImport } from './routes/ort.$id'
import { Route as SeiteIdRouteImport } from './routes/seite.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbgleichRoute = AbgleichRouteImport.update({
  id: '/abgleich',
  path: '/abgleich',
  getParentRoute: () => rootRouteImport,
} as any)
const EingangRoute = EingangRouteImport.update({
  id: '/eingang',
  path: '/eingang',
  getParentRoute: () => rootRouteImport,
} as any)
const StilRoute = StilRouteImport.update({
  id: '/stil',
  path: '/stil',
  getParentRoute: () => rootRouteImport,
} as any)
const BezirkKeyRoute = BezirkKeyRouteImport.update({
  id: '/bezirk/$key',
  path: '/bezirk/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtIdRoute = OrtIdRouteImport.update({
  id: '/ort/$id',
  path: '/ort/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeiteIdRoute = SeiteIdRouteImport.update({
  id: '/seite/$id',
  path: '/seite/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abgleich': typeof AbgleichRoute
  '/eingang': typeof EingangRoute
  '/stil': typeof StilRoute
  '/bezirk/$key': typeof BezirkKeyRoute
  '/ort/$id': typeof OrtIdRoute
  '/seite/$id': typeof SeiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abgleich': typeof AbgleichRoute
  '/eingang': typeof EingangRoute
  '/stil': typeof StilRoute
  '/bezirk/$key': typeof BezirkKeyRoute
  '/ort/$id': typeof OrtIdRoute
  '/seite/$id': typeof SeiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abgleich': typeof AbgleichRoute
  '/eingang': typeof EingangRoute
  '/stil': typeof StilRoute
  '/bezirk/$key': typeof BezirkKeyRoute
  '/ort/$id': typeof OrtIdRoute
  '/seite/$id': typeof SeiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abgleich'
    | '/eingang'
    | '/stil'
    | '/bezirk/$key'
    | '/ort/$id'
    | '/seite/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abgleich'
    | '/eingang'
    | '/stil'
    | '/bezirk/$key'
    | '/ort/$id'
    | '/seite/$id'
  id:
    | '__root__'
    | '/'
    | '/abgleich'
    | '/eingang'
    | '/stil'
    | '/bezirk/$key'
    | '/ort/$id'
    | '/seite/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbgleichRoute: typeof AbgleichRoute
  EingangRoute: typeof EingangRoute
  StilRoute: typeof StilRoute
  BezirkKeyRoute: typeof BezirkKeyRoute
  OrtIdRoute: typeof OrtIdRoute
  SeiteIdRoute: typeof SeiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abgleich': {
      id: '/abgleich'
      path: '/abgleich'
      fullPath: '/abgleich'
      preLoaderRoute: typeof AbgleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eingang': {
      id: '/eingang'
      path: '/eingang'
      fullPath: '/eingang'
      preLoaderRoute: typeof EingangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stil': {
      id: '/stil'
      path: '/stil'
      fullPath: '/stil'
      preLoaderRoute: typeof StilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bezirk/$key': {
      id: '/bezirk/$key'
      path: '/bezirk/$key'
      fullPath: '/bezirk/$key'
      preLoaderRoute: typeof BezirkKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ort/$id': {
      id: '/ort/$id'
      path: '/ort/$id'
      fullPath: '/ort/$id'
      preLoaderRoute: typeof OrtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seite/$id': {
      id: '/seite/$id'
      path: '/seite/$id'
      fullPath: '/seite/$id'
      preLoaderRoute: typeof SeiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbgleichRoute: AbgleichRoute,
  EingangRoute: EingangRoute,
  StilRoute: StilRoute,
  BezirkKeyRoute: BezirkKeyRoute,
  OrtIdRoute: OrtIdRoute,
  SeiteIdRoute: SeiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
